#TODO get the ENUMS working and come up with a good RegExp pattern for registry.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: entandokeycloakservers.entando.org
spec:
  group: entando.org
  version: v1alpha1
  names:
    kind: EntandoKeycloakServer
    plural: entandokeycloakservers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            imageName:
              type: string
            dbms:
              type: string
              pattern: '^(mysql|oracle|postgresql|none)$'
            tlsSecretName:
              type: string
            ingressHostName:
              type: string
              pattern: '^([A-Za-z0-9-]{1,63}\.)+[[A-Za-z0-9-]{1,63}$'
            entandoImageVersion:
              type: string
            replicas:
              type: integer
              minimum: 1
              maximum: 10
        entandoStatus: {}

