#TODO get the ENUMS working and come up with a good RegExp pattern for registry.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: entandoapps.entando.org
spec:
  group: entando.org
  version: v1
  names:
    kind: EntandoApp
    plural: entandoapps
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            standardServerImage:
              type: string
              pattern: '^(wildfly|eap|tomcat|jetty)$'
            customServerImage:
              type: string
            dbms:
              type: string
              pattern: '^(mysql|oracle|postgresql|none)$'
            tlsSecretName:
              type: string
              pattern: '^([a-z])+([a-z0-9-\.])*[a-z0-9]$'
            ingressHostName:
              type: string
              pattern: '^([A-Za-z0-9-]{1,63}\.)+[[A-Za-z0-9-]{1,63}$'
            entandoImageVersion:
              type: string
            replicas:
              type: integer
              minimum: 1
              maximum: 10
            keycloakSecretToUse:
              type: string
              pattern: '^([a-z])+([a-z0-9-\.])*[a-z0-9]$'
            clusterInfrastructureToUse:
              type: string
              pattern: '^([a-z])+([a-z0-9-\.])*[a-z0-9]$'
        entandoStatus: {}

