apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: entandodatabaseservices.entando.org
spec:
  group: entando.org
  version: v1
  names:
    kind: EntandoDatabaseService
    plural: entandodatabaseservices
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            host:
              type: string
              pattern: '^([A-Za-z0-9-]{1,63}\.)+[[A-Za-z0-9-]{1,63}$'
            port:
              type: integer
            databaseName:
              type: string
            secretName:
              type: string
            dbms:
              type: string
              pattern: '^(mysql|oracle|postgresql|none)$'
        entandoStatus: {}