apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: entandoplugins.entando.org
spec:
  group: entando.org
  version: v1alpha1
  names:
    kind: EntandoPlugin
    plural: entandoplugins
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            entandoAppName:
              type: string
            replicas:
              type: integer
              minimum: 1
              maximum: 10
            image:
              type: string
            ingressPath:
              type: string
            healthCheckPath:
              type: string
            dbms:
              type: string
            securityLevel:
              type: string
            parameters:
              type: object
            connectionConfigNames:
              type: array
              items:
                type: string
            roles:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                  name:
                    type: string
            permissions:
              type: array
              items:
                type: object
                properties:
                  clientId:
                    type: string
                  role:
                    type: string
        entandoStatus: {}
