#TODO get the ENUMS working and come up with a good RegExp pattern for registry.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: externaldatabases.entando.org
spec:
  group: entando.org
  version: v1alpha1
  names:
    kind: ExternalDatabase
    plural: externaldatabases
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            host:
              type: string
              pattern: '^([A-Za-z0-9-]{1,63}\.)+[[A-Za-z0-9-]{1,63}$'
            port:
              type: integer
            databaseName:
              type: string
            secretName:
              type: string
            dbms:
              type: string
        entandoStatus: {}
