apiVersion: rbac.authorization.k8s.io/v1
kind: CuslterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-default-crd-viewer
  namespace:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: entando-crd-viewer
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}