# !! File must end with empty line !!
dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: entando-k8s-keycloak-controller
  repository: file://../entando-k8s-keycloak-controller
