---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "external-postgresql"
spec:
  ports:
    - port: 5432
      targetPort: 5432
selector: {}
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "external-postgresql"
subsets:
  - addresses:
      - ip: "172.30.7.132"
    ports:
      - port: 5432
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "external-mysql"
spec:
  ports:
    - port: 3306
      targetPort: 3306
selector: {}
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "external-mysql"
subsets:
  - addresses:
      - ip: "172.30.71.59"
    ports:
      - port: 3306
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "external-oracle"
spec:
  ports:
    - port: 1521
      targetPort: 1521
selector: {}
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "external-oracle"
subsets:
  - addresses:
      - ip: "172.30.12.235"
    ports:
      - port: 1521
