apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.redhatRegistryCredentials }}
kind: Secret
metadata:
  name: redhat-registry
  namespace: entando-k8s-controller-coordinator-carcpr65
type: kubernetes.io/dockerconfigjson
