apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: entando/entando-k8s-operator-common
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: jvm
  build:
    artifacts:
    - image: entando/entando-k8s-operator-common
      docker:
        dockerfile: Dockerfile.jvm
        buildArgs:
          VERSION: "{{ .VERSION}}"
- name: native
  build:
    artifacts:
    - image: entando/entando-k8s-operator-common
      docker:
        dockerfile: Dockerfile.native
        buildArgs:
          VERSION: "{{ .VERSION}}"
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: entando-k8s-operator-common
        chartPath: charts/entando-k8s-operator-common
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.DIGEST_HEX}}'
