kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: entando-test-crd-viewer
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch