apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: entando-operator-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: entando-operator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}