cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

preview:
  image:
    repository:
    tag:
    pullPolicy: IfNotPresent

operator:
  registry: docker-registry.default.svc:5000
  namespaceOverride:
  defaultRoutingSuffix: apps.serv.run
  podReadinessTimeoutSeconds: 900
  podCompletionTimeoutSeconds: 900
  disableKeycloakSslRequirement: true
  imageNamespace: entando
