apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        stepTemplate:
          name: ""
          resources: {}
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
            readOnly: true
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - args:
          - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
          command:
          - /bin/sh
          - -c
          env:
          - name: BUILDER_JX_IMAGE
            value: ghcr.io/jenkins-x/builder-jx:2.1.155-778-patch3
          - name: ENTANDO_DOCKER_IMAGE_INFO_CONFIGMAP
            value: entando-docker-image-info-v6.3
          - name: PIPELINE_CODE
            value: cm
          - name: SKIP_OWASP
            value: "false"
          - name: TEST_DEPLOYMENT
            value: "false"
          - name: KANIKO_FLAGS
            value: --skip-unused-stages --snapshotMode=redo
          - name: ENTANDO_TEST_REDHAT_REGISTRY_CREDENTIALS
            valueFrom:
              secretKeyRef:
                key: redhat.registry.credentials
                name: entando-jx-common-secret
          - name: EXECUTABLE_TYPE
            valueFrom:
              secretKeyRef:
                key: executable.type
                name: entando-jx-common-secret
          image: gcr.io/jenkinsxio/builder-jx:2.1.155-778
          name: setup-builder-home
          resources: {}
        - args:
          - gitops
          - variables
          command:
          - jx
          image: gcr.io/jenkinsxio/jx-cli:latest
          name: jx-variables
          resources: {}
        - args:
          - mvn versions:set -DnewVersion=$PREVIEW_VERSION
          command:
          - /bin/sh
          - -c
          env:
          - name: BUILDER_JX_IMAGE
            value: ghcr.io/jenkins-x/builder-jx:2.1.155-778-patch3
          - name: ENTANDO_DOCKER_IMAGE_INFO_CONFIGMAP
            value: entando-docker-image-info-v6.3
          - name: PIPELINE_CODE
            value: cm
          - name: SKIP_OWASP
            value: "false"
          - name: TEST_DEPLOYMENT
            value: "false"
          - name: KANIKO_FLAGS
            value: --skip-unused-stages --snapshotMode=redo
          - name: ENTANDO_TEST_REDHAT_REGISTRY_CREDENTIALS
            valueFrom:
              secretKeyRef:
                key: redhat.registry.credentials
                name: entando-jx-common-secret
          - name: EXECUTABLE_TYPE
            valueFrom:
              secretKeyRef:
                key: executable.type
                name: entando-jx-common-secret
          image: entando-jx-maven
          name: build-set-version
          resources: {}
        - args:
          - fix-git-branches
          command:
          - /bin/sh
          - -c
          env:
          - name: BUILDER_JX_IMAGE
            value: ghcr.io/jenkins-x/builder-jx:2.1.155-778-patch3
          - name: ENTANDO_DOCKER_IMAGE_INFO_CONFIGMAP
            value: entando-docker-image-info-v6.3
          - name: PIPELINE_CODE
            value: cm
          - name: SKIP_OWASP
            value: "false"
          - name: TEST_DEPLOYMENT
            value: "false"
          - name: KANIKO_FLAGS
            value: --skip-unused-stages --snapshotMode=redo
          - name: ENTANDO_TEST_REDHAT_REGISTRY_CREDENTIALS
            valueFrom:
              secretKeyRef:
                key: redhat.registry.credentials
                name: entando-jx-common-secret
          - name: EXECUTABLE_TYPE
            valueFrom:
              secretKeyRef:
                key: executable.type
                name: entando-jx-common-secret
          image: entando-jx-maven
          name: build-fix-git-for-sonar
          resources: {}
        - args:
          - mvn-verify-pr
          command:
          - /bin/sh
          - -c
          env:
          - name: BUILDER_JX_IMAGE
            value: ghcr.io/jenkins-x/builder-jx:2.1.155-778-patch3
          - name: ENTANDO_DOCKER_IMAGE_INFO_CONFIGMAP
            value: entando-docker-image-info-v6.3
          - name: PIPELINE_CODE
            value: cm
          - name: SKIP_OWASP
            value: "false"
          - name: TEST_DEPLOYMENT
            value: "false"
          - name: KANIKO_FLAGS
            value: --skip-unused-stages --snapshotMode=redo
          - name: ENTANDO_TEST_REDHAT_REGISTRY_CREDENTIALS
            valueFrom:
              secretKeyRef:
                key: redhat.registry.credentials
                name: entando-jx-common-secret
          - name: EXECUTABLE_TYPE
            valueFrom:
              secretKeyRef:
                key: executable.type
                name: entando-jx-common-secret
          image: entando-jx-maven
          name: build-mvn-verify-pr
          resources: {}
        - args:
          - skaffold-build
          command:
          - /bin/sh
          - -c
          env:
          - name: BUILDER_JX_IMAGE
            value: ghcr.io/jenkins-x/builder-jx:2.1.155-778-patch3
          - name: ENTANDO_DOCKER_IMAGE_INFO_CONFIGMAP
            value: entando-docker-image-info-v6.3
          - name: PIPELINE_CODE
            value: cm
          - name: SKIP_OWASP
            value: "false"
          - name: TEST_DEPLOYMENT
            value: "false"
          - name: KANIKO_FLAGS
            value: --skip-unused-stages --snapshotMode=redo
          - name: ENTANDO_TEST_REDHAT_REGISTRY_CREDENTIALS
            valueFrom:
              secretKeyRef:
                key: redhat.registry.credentials
                name: entando-jx-common-secret
          - name: EXECUTABLE_TYPE
            valueFrom:
              secretKeyRef:
                key: executable.type
                name: entando-jx-common-secret
          image: entando-jx-maven
          name: build-container-build
          resources: {}
        volumes:
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate:
    ImagePullSecrets: null
    hostNetwork: false
    schedulerName: ""
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
