apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        stepTemplate:
          name: ""
          resources: {}
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
            readOnly: true
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - args:
          - -c
          - echo $(jx-release-version) > VERSION
          command:
          - /bin/sh
          image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: next-version
          resources: {}
        - args:
          - -c
          - mvn versions:set -DnewVersion=$(cat VERSION)
          command:
          - /bin/sh
          image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: set-version
          resources: {}
        - args:
          - -c
          - jx step tag --version $(cat VERSION)
          command:
          - /bin/sh
          image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: tag-version
          resources: {}
        - args:
          - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
          command:
          - /bin/sh
          - -c
          env:
          - name: BUILDER_JX_IMAGE
            value: ghcr.io/jenkins-x/builder-jx:2.1.155-778-patch3
          - name: ENTANDO_DOCKER_IMAGE_INFO_CONFIGMAP
            value: entando-docker-image-info-v6.3
          - name: PIPELINE_CODE
            value: cm
          - name: SKIP_OWASP
            value: "false"
          - name: TEST_DEPLOYMENT
            value: "false"
          - name: KANIKO_FLAGS
            value: --skip-unused-stages --snapshotMode=redo
          - name: ENTANDO_TEST_REDHAT_REGISTRY_CREDENTIALS
            valueFrom:
              secretKeyRef:
                key: redhat.registry.credentials
                name: entando-jx-common-secret
          - name: EXECUTABLE_TYPE
            valueFrom:
              secretKeyRef:
                key: executable.type
                name: entando-jx-common-secret
          image: gcr.io/jenkinsxio/builder-jx:2.1.155-778
          name: setup-builder-home
          resources: {}
        - args:
          - gitops
          - variables
          command:
          - jx
          image: gcr.io/jenkinsxio/jx-cli:latest
          name: jx-variables
          resources: {}
        - args:
          - git fetch origin
          command:
          - /bin/sh
          - -c
          env:
          - name: BUILDER_JX_IMAGE
            value: ghcr.io/jenkins-x/builder-jx:2.1.155-778-patch3
          - name: ENTANDO_DOCKER_IMAGE_INFO_CONFIGMAP
            value: entando-docker-image-info-v6.3
          - name: PIPELINE_CODE
            value: cm
          - name: SKIP_OWASP
            value: "false"
          - name: TEST_DEPLOYMENT
            value: "false"
          - name: KANIKO_FLAGS
            value: --skip-unused-stages --snapshotMode=redo
          - name: ENTANDO_TEST_REDHAT_REGISTRY_CREDENTIALS
            valueFrom:
              secretKeyRef:
                key: redhat.registry.credentials
                name: entando-jx-common-secret
          - name: EXECUTABLE_TYPE
            valueFrom:
              secretKeyRef:
                key: executable.type
                name: entando-jx-common-secret
          image: entando-jx-maven
          name: build-fetch-history-for-sonar
          resources: {}
        - args:
          - mvn-deploy-release -P${EXECUTABLE_TYPE}
          command:
          - /bin/sh
          - -c
          env:
          - name: BUILDER_JX_IMAGE
            value: ghcr.io/jenkins-x/builder-jx:2.1.155-778-patch3
          - name: ENTANDO_DOCKER_IMAGE_INFO_CONFIGMAP
            value: entando-docker-image-info-v6.3
          - name: PIPELINE_CODE
            value: cm
          - name: SKIP_OWASP
            value: "false"
          - name: TEST_DEPLOYMENT
            value: "false"
          - name: KANIKO_FLAGS
            value: --skip-unused-stages --snapshotMode=redo
          - name: ENTANDO_TEST_REDHAT_REGISTRY_CREDENTIALS
            valueFrom:
              secretKeyRef:
                key: redhat.registry.credentials
                name: entando-jx-common-secret
          - name: EXECUTABLE_TYPE
            valueFrom:
              secretKeyRef:
                key: executable.type
                name: entando-jx-common-secret
          image: entando-jx-maven
          name: build-mvn-deploy-release
          resources: {}
        - args:
          - skaffold-build
          command:
          - /bin/sh
          - -c
          env:
          - name: BUILDER_JX_IMAGE
            value: ghcr.io/jenkins-x/builder-jx:2.1.155-778-patch3
          - name: ENTANDO_DOCKER_IMAGE_INFO_CONFIGMAP
            value: entando-docker-image-info-v6.3
          - name: PIPELINE_CODE
            value: cm
          - name: SKIP_OWASP
            value: "false"
          - name: TEST_DEPLOYMENT
            value: "false"
          - name: KANIKO_FLAGS
            value: --skip-unused-stages --snapshotMode=redo
          - name: ENTANDO_TEST_REDHAT_REGISTRY_CREDENTIALS
            valueFrom:
              secretKeyRef:
                key: redhat.registry.credentials
                name: entando-jx-common-secret
          - name: EXECUTABLE_TYPE
            valueFrom:
              secretKeyRef:
                key: executable.type
                name: entando-jx-common-secret
          image: entando-jx-maven
          name: build-container-build
          resources: {}
        - args:
          - jx step changelog --version v${VERSION}
          command:
          - /bin/sh
          - -c
          env:
          - name: BUILDER_JX_IMAGE
            value: ghcr.io/jenkins-x/builder-jx:2.1.155-778-patch3
          - name: ENTANDO_DOCKER_IMAGE_INFO_CONFIGMAP
            value: entando-docker-image-info-v6.3
          - name: PIPELINE_CODE
            value: cm
          - name: SKIP_OWASP
            value: "false"
          - name: TEST_DEPLOYMENT
            value: "false"
          - name: KANIKO_FLAGS
            value: --skip-unused-stages --snapshotMode=redo
          - name: ENTANDO_TEST_REDHAT_REGISTRY_CREDENTIALS
            valueFrom:
              secretKeyRef:
                key: redhat.registry.credentials
                name: entando-jx-common-secret
          - name: EXECUTABLE_TYPE
            valueFrom:
              secretKeyRef:
                key: executable.type
                name: entando-jx-common-secret
          image: entando-jx-maven
          name: promote-changelog
          resources: {}
        volumes:
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate:
    ImagePullSecrets: null
    hostNetwork: false
    schedulerName: ""
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
