{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      volumes:
        - name: entando-tls-volume
          secret:
            secretName: entando-tls-secret
        - name: entando-ca-cert-volume
          secret:
            secretName: entando-ca-cert-secret
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: entando-tls-volume
            mountPath: /etc/entando/tls
          - name: entando-ca-cert-volume
            mountPath: /etc/entando/ca
        env:
          - name: ENTANDO_K8S_OPERATOR_REGISTRY
            value: "{{ .Values.operator.registry }}"
          - name: ENTANDO_OPERATOR_NAMESPACE_OVERRIDE
            value: "{{ .Release.Namespace }}"
          - name: ENTANDO_DEFAULT_ROUTING_SUFFIX
            value: "{{ .Values.operator.defaultRoutingSuffix }}"
          - name: ENTANDO_POD_READINESS_TIMEOUT_SECONDS
            value: "{{ .Values.operator.podReadinessTimeoutSeconds }}"
          - name: ENTANDO_POD_COMPLETION_TIMEOUT_SECONDS
            value: "{{ .Values.operator.podCompletionTimeoutSeconds }}"
          - name: ENTANDO_DISABLE_KEYCLOAK_SSL_REQUIREMENT
            value: "{{ .Values.operator.disableKeycloakSslRequirement }}"
          - name: ENTANDO_K8S_OPERATOR_IMAGE_NAMESPACE
            value: "{{ .Values.operator.imageNamespace }}"
          - name: ENTANDO_CA_CERT_PATHS
            value: "/etc/entando/ca/ca.crt"
          - name: ENTANDO_PATH_TO_TLS_KEYPAIR
            value: "/etc/entando/tls"
        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/EntandoControllerCoordinator.ready
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          exec:
            command:
              - cat
              - /tmp/EntandoControllerCoordinator.ready
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
{{- end }}
