apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: entando-operator
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - entando.org
    resources:
      - entandokeycloakservers
      - entandokeycloakservers/finalizers
      - entandoclusterinfrastructures
      - entandoclusterinfrastructures/finalizers
      - entandoapps
      - entandoapps/finalizers
      - entandoplugins
      - entandoplugins/finalizers
      - entandoapppluginlinks
      - entandoapppluginlinks/finalizers
      - entandodatabaseservices
      - entandodatabaseservices/finalizers
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - "*"
{{- if .Values.supportOpenshift }}
  - apiGroups:
      - route.openshift.io
    resources:
      - "routes"
      - "routes/custom-host"
    verbs:
      - "*"
{{- end }}
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get