apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: entando-operator
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - entando.org
    resources:
      - entandokeycloakservers
      - entandoclusterinfrastructures
      - entandoapps
      - entandoplugins
      - entandoapppluginlinks
      - entandodatabaseservices
    verbs:
      - update
      - list
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get